// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oenafczmuxpfdfupwmkt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9lbmFmY3ptdXhwZmRmdXB3bWt0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk3NDY3NDksImV4cCI6MjA1NTMyMjc0OX0.x6tM3AcqHROzTJ9nA2X9QYlZeBnw7sInT3iNH6ZynL4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);